BEGIN;

-- Persistent client-GET fixtures. RFC 5737 documentation addresses and the
-- OFFLINE state prevent clients from mistaking these records for joinable
-- production servers.
INSERT INTO game_servers (
    id,
    instance_id,
    display_name,
    region,
    mode,
    version,
    public_host,
    public_port,
    max_players,
    player_count,
    state,
    server_token_hash,
    registration_issuer,
    token_expires_at,
    token_revoked_at,
    last_heartbeat_at,
    created_at,
    updated_at
) VALUES
    (
        'gs_example_hk_casual_01',
        'client-get-fixture-hk-casual-01',
        '[示例] 香港休闲服务器',
        'asia-hk',
        'casual',
        '0.0.0-fixture',
        '192.0.2.10',
        7777,
        16,
        0,
        'OFFLINE',
        decode(repeat('01', 32), 'hex'),
        'CLIENT_GET_FIXTURE',
        NOW() + INTERVAL '1 year',
        NOW(),
        NOW(),
        NOW(),
        NOW()
    ),
    (
        'gs_example_sg_ranked_01',
        'client-get-fixture-sg-ranked-01',
        '[示例] 新加坡竞技服务器',
        'asia-sg',
        'ranked',
        '0.0.0-fixture',
        '198.51.100.20',
        7778,
        32,
        0,
        'OFFLINE',
        decode(repeat('02', 32), 'hex'),
        'CLIENT_GET_FIXTURE',
        NOW() + INTERVAL '1 year',
        NOW(),
        NOW(),
        NOW(),
        NOW()
    ),
    (
        'gs_example_jp_coop_01',
        'client-get-fixture-jp-coop-01',
        '[示例] 东京合作服务器',
        'asia-jp',
        'coop',
        '0.0.0-fixture',
        '203.0.113.30',
        7779,
        8,
        0,
        'OFFLINE',
        decode(repeat('03', 32), 'hex'),
        'CLIENT_GET_FIXTURE',
        NOW() + INTERVAL '1 year',
        NOW(),
        NOW(),
        NOW(),
        NOW()
    ),
    (
        'gs_example_us_survival_01',
        'client-get-fixture-us-survival-01',
        '[示例] 美西生存服务器',
        'us-west',
        'survival',
        '0.0.0-fixture',
        '192.0.2.40',
        7780,
        64,
        0,
        'OFFLINE',
        decode(repeat('04', 32), 'hex'),
        'CLIENT_GET_FIXTURE',
        NOW() + INTERVAL '1 year',
        NOW(),
        NOW(),
        NOW(),
        NOW()
    )
ON CONFLICT (instance_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    region = EXCLUDED.region,
    mode = EXCLUDED.mode,
    version = EXCLUDED.version,
    public_host = EXCLUDED.public_host,
    public_port = EXCLUDED.public_port,
    max_players = EXCLUDED.max_players,
    player_count = EXCLUDED.player_count,
    state = EXCLUDED.state,
    server_token_hash = EXCLUDED.server_token_hash,
    registration_issuer = EXCLUDED.registration_issuer,
    token_expires_at = EXCLUDED.token_expires_at,
    token_revoked_at = EXCLUDED.token_revoked_at,
    last_heartbeat_at = EXCLUDED.last_heartbeat_at,
    updated_at = EXCLUDED.updated_at;

COMMIT;
