$ErrorActionPreference = 'Stop'

go fmt ./...
go vet ./...
go test ./...
New-Item -ItemType Directory -Force -Path ..\.tmp\bin | Out-Null
go build -o ..\.tmp\bin\control-plane.exe ./cmd/control-plane
