[CmdletBinding()]
param(
    [string]$SdkPath = (Join-Path $PSScriptRoot '..\..\Payload\SDK'),
    [string]$OutputDirectory = (Join-Path $PSScriptRoot 'output')
)

$ErrorActionPreference = 'Stop'

$resolvedSdkPath = [System.IO.Path]::GetFullPath($SdkPath)
$resolvedOutputDirectory = [System.IO.Path]::GetFullPath($OutputDirectory)
if (-not (Test-Path -LiteralPath $resolvedSdkPath -PathType Container)) {
    throw "SDK directory does not exist: $resolvedSdkPath"
}

New-Item -ItemType Directory -Force -Path $resolvedOutputDirectory | Out-Null

$categories = [ordered]@{
    weapons = @('PBWeapon', 'Weapon', 'Inventory', 'ApplyPart', 'WeaponPart', 'Attachment')
    roles = @('PBRole', 'Role', 'EPBRole', 'SelectRole', 'ServerConfirmRoleSelection')
    inventory = @('Inventory', 'Loadout', 'Equipment', 'Pylon', 'Utility', 'Module', 'Gadget')
}

$sourceFiles = @(Get-ChildItem -LiteralPath $resolvedSdkPath -Recurse -File |
    Where-Object { $_.Extension -in @('.hpp', '.cpp') } |
    Sort-Object FullName)

$sdkPrefix = $resolvedSdkPath.TrimEnd([System.IO.Path]::DirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)

foreach ($category in $categories.GetEnumerator()) {
    $pattern = '\b(?:' + (($category.Value | ForEach-Object { [regex]::Escape($_) }) -join '|') + ')\b'
    $outputPath = Join-Path $resolvedOutputDirectory ($category.Key + '.txt')
    $writer = New-Object System.IO.StreamWriter($outputPath, $false, $utf8WithoutBom)
    try {
        $writer.WriteLine('# Generated by Tools/SdkSearch/find-loadout-symbols.ps1')
        foreach ($file in $sourceFiles) {
            $relativePath = $file.FullName
            if ($relativePath.StartsWith($sdkPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
                $relativePath = $relativePath.Substring($sdkPrefix.Length)
            }

            $lineNumber = 0
            foreach ($line in [System.IO.File]::ReadLines($file.FullName)) {
                $lineNumber++
                if ($line -match $pattern) {
                    $writer.WriteLine('')
                    $writer.WriteLine("File: $relativePath")
                    $writer.WriteLine("Line: $lineNumber")
                    $writer.WriteLine('Text: ' + $line.Trim())
                    $writer.WriteLine('----------------------------------------')
                }
            }
        }
    }
    finally {
        $writer.Dispose()
    }
    Write-Host "Wrote $outputPath"
}
