#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Option_VIbration

#include "Basic.hpp"

#include "ProjectBoundary_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Option_VIbration.Option_VIbration_C
// 0x0008 (0x00C0 - 0x00B8)
class UOption_VIbration_C final : public UPBBoolSettingOption
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Option_VIbration(int32 EntryPoint);
	void K2_Modify(bool bIsDependencyChanged);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Option_VIbration_C">();
	}
	static class UOption_VIbration_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOption_VIbration_C>();
	}
};
static_assert(alignof(UOption_VIbration_C) == 0x000008, "Wrong alignment on UOption_VIbration_C");
static_assert(sizeof(UOption_VIbration_C) == 0x0000C0, "Wrong size on UOption_VIbration_C");
static_assert(offsetof(UOption_VIbration_C, UberGraphFrame) == 0x0000B8, "Member 'UOption_VIbration_C::UberGraphFrame' has a wrong offset!");

}

