#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Option_ActivateMobilityModule

#include "Basic.hpp"

#include "ProjectBoundary_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Option_ActivateMobilityModule.Option_ActivateMobilityModule_C
// 0x0000 (0x00B8 - 0x00B8)
class UOption_ActivateMobilityModule_C final : public UPBBindingKeySettingOption
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Option_ActivateMobilityModule_C">();
	}
	static class UOption_ActivateMobilityModule_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOption_ActivateMobilityModule_C>();
	}
};
static_assert(alignof(UOption_ActivateMobilityModule_C) == 0x000008, "Wrong alignment on UOption_ActivateMobilityModule_C");
static_assert(sizeof(UOption_ActivateMobilityModule_C) == 0x0000B8, "Wrong size on UOption_ActivateMobilityModule_C");

}

