#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Option_Language

#include "Basic.hpp"

#include "Option_Language_classes.hpp"
#include "Option_Language_parameters.hpp"


namespace SDK
{

// Function Option_Language.Option_Language_C.ExecuteUbergraph_Option_Language
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOption_Language_C::ExecuteUbergraph_Option_Language(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Option_Language_C", "ExecuteUbergraph_Option_Language");

	Params::Option_Language_C_ExecuteUbergraph_Option_Language Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Option_Language.Option_Language_C.K2_Modify
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsDependencyChanged                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UOption_Language_C::K2_Modify(bool bIsDependencyChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Option_Language_C", "K2_Modify");

	Params::Option_Language_C_K2_Modify Parms{};

	Parms.bIsDependencyChanged = bIsDependencyChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Option_Language.Option_Language_C.K2_Apply
// (Event, Protected, BlueprintEvent)

void UOption_Language_C::K2_Apply()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Option_Language_C", "K2_Apply");

	UObject::ProcessEvent(Func, nullptr);
}

}

