#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PBEMPGrenade_BP

#include "Basic.hpp"

#include "ProjectBoundary_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PBEMPGrenade_BP.PBEMPGrenade_BP_C
// 0x0000 (0x0758 - 0x0758)
class APBEMPGrenade_BP_C final : public APBEMPGrenade
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PBEMPGrenade_BP_C">();
	}
	static class APBEMPGrenade_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APBEMPGrenade_BP_C>();
	}
};
static_assert(alignof(APBEMPGrenade_BP_C) == 0x000008, "Wrong alignment on APBEMPGrenade_BP_C");
static_assert(sizeof(APBEMPGrenade_BP_C) == 0x000758, "Wrong size on APBEMPGrenade_BP_C");

}

