#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_ChatWidget

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "ProjectBoundary_structs.hpp"
#include "InputCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function UMG_ChatWidget.UMG_ChatWidget_C.ExecuteUbergraph_UMG_ChatWidget
// 0x0270 (0x0270 - 0x0000)
struct UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPBOptions*                             CallFunc_GetEngineSubsystem_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPBOptions*                             CallFunc_GetEngineSubsystem_ReturnValue_1;         // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_Event_bWasSuccessful;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPBChatMessage                         K2Node_Event_NewMessage_1;                         // 0x0030(0x0038)(ConstParm)
	struct FPBChatMessage                         K2Node_Event_NewMessage;                           // 0x0068(0x0038)(ConstParm)
	TArray<struct FPBChatMessage>                 K2Node_Event_SavedMessages;                        // 0x00A0(0x0010)(ConstParm, ReferenceParm)
	class FText                                   K2Node_ComponentBoundEvent_Text_1;                 // 0x00B0(0x0018)(ConstParm)
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x00C8(0x0018)(ConstParm)
	ETextCommit                                   K2Node_ComponentBoundEvent_CommitMethod;           // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F9[0x3];                                       // 0x00F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Len_ReturnValue;                          // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0108(0x0018)()
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0120(0x0038)(IsPlainOldData, NoDestructor)
	struct FPointerEvent                          K2Node_Event_MouseEvent;                           // 0x0158(0x0070)(ConstParm)
	bool                                          CallFunc_IsMainMenu_IsMainMenu;                    // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C9[0x3];                                      // 0x01C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool bQuitgame)>               K2Node_CreateDelegate_OutputDelegate_1;            // 0x01CC(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class FName StateName)>        K2Node_CreateDelegate_OutputDelegate_2;            // 0x01DC(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_1EC[0x4];                                      // 0x01EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_StateName;                      // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APBPlayerController*                    K2Node_DynamicCast_AsPBPlayer_Controller;          // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_209[0x7];                                      // 0x0209(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue_1;                    // 0x0210(0x0018)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_229[0x3];                                      // 0x0229(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class FName PageName)>         K2Node_CreateDelegate_OutputDelegate_3;            // 0x022C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x023C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x024C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_25C[0x4];                                      // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPBMainMenuManager*                     CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget");
static_assert(sizeof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget) == 0x000270, "Wrong size on UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, EntryPoint) == 0x000000, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_GetEngineSubsystem_ReturnValue) == 0x000008, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_GetEngineSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_GetEngineSubsystem_ReturnValue_1) == 0x000010, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_GetEngineSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_CreateDelegate_OutputDelegate) == 0x000018, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_Event_bWasSuccessful) == 0x000028, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_Event_bWasSuccessful' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_Event_NewMessage_1) == 0x000030, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_Event_NewMessage_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_Event_NewMessage) == 0x000068, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_Event_NewMessage' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_Event_SavedMessages) == 0x0000A0, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_Event_SavedMessages' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_ComponentBoundEvent_Text_1) == 0x0000B0, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_ComponentBoundEvent_Text_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_ComponentBoundEvent_Text) == 0x0000C8, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_ComponentBoundEvent_Text' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_ComponentBoundEvent_CommitMethod) == 0x0000E0, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_ComponentBoundEvent_CommitMethod' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_Conv_TextToString_ReturnValue) == 0x0000E8, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_SwitchEnum_CmpSuccess) == 0x0000F8, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_Len_ReturnValue) == 0x0000FC, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_Len_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000100, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_GetText_ReturnValue) == 0x000108, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_Event_MyGeometry) == 0x000120, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_Event_MouseEvent) == 0x000158, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_Event_MouseEvent' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_IsMainMenu_IsMainMenu) == 0x0001C8, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_IsMainMenu_IsMainMenu' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_CreateDelegate_OutputDelegate_1) == 0x0001CC, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_CreateDelegate_OutputDelegate_2) == 0x0001DC, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_GetPlayerController_ReturnValue) == 0x0001F0, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_CustomEvent_StateName) == 0x0001F8, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_CustomEvent_StateName' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_DynamicCast_AsPBPlayer_Controller) == 0x000200, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_DynamicCast_AsPBPlayer_Controller' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_DynamicCast_bSuccess) == 0x000208, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_GetText_ReturnValue_1) == 0x000210, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_GetText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_TextIsEmpty_ReturnValue) == 0x000228, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_CreateDelegate_OutputDelegate_3) == 0x00022C, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_CreateDelegate_OutputDelegate_4) == 0x00023C, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_CreateDelegate_OutputDelegate_5) == 0x00024C, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000260, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget, K2Node_Event_IsDesignTime) == 0x000268, "Member 'UMG_ChatWidget_C_ExecuteUbergraph_UMG_ChatWidget::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UMG_ChatWidget_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_ChatWidget_C_PreConstruct) == 0x000001, "Wrong alignment on UMG_ChatWidget_C_PreConstruct");
static_assert(sizeof(UMG_ChatWidget_C_PreConstruct) == 0x000001, "Wrong size on UMG_ChatWidget_C_PreConstruct");
static_assert(offsetof(UMG_ChatWidget_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UMG_ChatWidget_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.OnStateNameChange
// 0x0008 (0x0008 - 0x0000)
struct UMG_ChatWidget_C_OnStateNameChange final
{
public:
	class FName                                   StateName;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_OnStateNameChange) == 0x000004, "Wrong alignment on UMG_ChatWidget_C_OnStateNameChange");
static_assert(sizeof(UMG_ChatWidget_C_OnStateNameChange) == 0x000008, "Wrong size on UMG_ChatWidget_C_OnStateNameChange");
static_assert(offsetof(UMG_ChatWidget_C_OnStateNameChange, StateName) == 0x000000, "Member 'UMG_ChatWidget_C_OnStateNameChange::StateName' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.OnMouseEnter
// 0x00A8 (0x00A8 - 0x0000)
struct UMG_ChatWidget_C_OnMouseEnter final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0038(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UMG_ChatWidget_C_OnMouseEnter) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_OnMouseEnter");
static_assert(sizeof(UMG_ChatWidget_C_OnMouseEnter) == 0x0000A8, "Wrong size on UMG_ChatWidget_C_OnMouseEnter");
static_assert(offsetof(UMG_ChatWidget_C_OnMouseEnter, MyGeometry) == 0x000000, "Member 'UMG_ChatWidget_C_OnMouseEnter::MyGeometry' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnMouseEnter, MouseEvent) == 0x000038, "Member 'UMG_ChatWidget_C_OnMouseEnter::MouseEvent' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	ETextCommit                                   CommitMethod;                                      // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature");
static_assert(sizeof(UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature) == 0x000020, "Wrong size on UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature");
static_assert(offsetof(UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature, Text) == 0x000000, "Member 'UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature::Text' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature, CommitMethod) == 0x000018, "Member 'UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_4_OnEditableTextCommittedEvent__DelegateSignature::CommitMethod' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_3_OnEditableTextChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_3_OnEditableTextChangedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_3_OnEditableTextChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_3_OnEditableTextChangedEvent__DelegateSignature");
static_assert(sizeof(UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_3_OnEditableTextChangedEvent__DelegateSignature) == 0x000018, "Wrong size on UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_3_OnEditableTextChangedEvent__DelegateSignature");
static_assert(offsetof(UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_3_OnEditableTextChangedEvent__DelegateSignature, Text) == 0x000000, "Member 'UMG_ChatWidget_C_BndEvt__UMG_Chat_Widget_EditableText_Message_K2Node_ComponentBoundEvent_3_OnEditableTextChangedEvent__DelegateSignature::Text' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.K2_RefreshSavedMessages
// 0x0010 (0x0010 - 0x0000)
struct UMG_ChatWidget_C_K2_RefreshSavedMessages final
{
public:
	TArray<struct FPBChatMessage>                 SavedMessages;                                     // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UMG_ChatWidget_C_K2_RefreshSavedMessages) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_K2_RefreshSavedMessages");
static_assert(sizeof(UMG_ChatWidget_C_K2_RefreshSavedMessages) == 0x000010, "Wrong size on UMG_ChatWidget_C_K2_RefreshSavedMessages");
static_assert(offsetof(UMG_ChatWidget_C_K2_RefreshSavedMessages, SavedMessages) == 0x000000, "Member 'UMG_ChatWidget_C_K2_RefreshSavedMessages::SavedMessages' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.K2_MessageReceived
// 0x0038 (0x0038 - 0x0000)
struct UMG_ChatWidget_C_K2_MessageReceived final
{
public:
	struct FPBChatMessage                         NewMessage;                                        // 0x0000(0x0038)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UMG_ChatWidget_C_K2_MessageReceived) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_K2_MessageReceived");
static_assert(sizeof(UMG_ChatWidget_C_K2_MessageReceived) == 0x000038, "Wrong size on UMG_ChatWidget_C_K2_MessageReceived");
static_assert(offsetof(UMG_ChatWidget_C_K2_MessageReceived, NewMessage) == 0x000000, "Member 'UMG_ChatWidget_C_K2_MessageReceived::NewMessage' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.K2_MessageSent
// 0x0040 (0x0040 - 0x0000)
struct UMG_ChatWidget_C_K2_MessageSent final
{
public:
	bool                                          bWasSuccessful;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPBChatMessage                         NewMessage;                                        // 0x0008(0x0038)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UMG_ChatWidget_C_K2_MessageSent) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_K2_MessageSent");
static_assert(sizeof(UMG_ChatWidget_C_K2_MessageSent) == 0x000040, "Wrong size on UMG_ChatWidget_C_K2_MessageSent");
static_assert(offsetof(UMG_ChatWidget_C_K2_MessageSent, bWasSuccessful) == 0x000000, "Member 'UMG_ChatWidget_C_K2_MessageSent::bWasSuccessful' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_K2_MessageSent, NewMessage) == 0x000008, "Member 'UMG_ChatWidget_C_K2_MessageSent::NewMessage' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.OnKeyDown
// 0x0308 (0x0308 - 0x0000)
struct UMG_ChatWidget_C_OnKeyDown final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FKeyEvent                              InKeyEvent;                                        // 0x0038(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FEventReply                            ReturnValue;                                       // 0x0070(0x00B8)(Parm, OutParm, ReturnParm)
	struct FKey                                   LocalKey;                                          // 0x0128(0x0018)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FKey                                   CallFunc_GetKey_ReturnValue;                       // 0x0140(0x0018)(HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0160(0x00B8)()
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue;            // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_219[0x7];                                      // 0x0219(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPBOptions*                             CallFunc_GetEngineSubsystem_ReturnValue;           // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0228(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22C[0x4];                                      // 0x022C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FKey>                           CallFunc_GetKeysOfInput_ReturnValue;               // 0x0230(0x0010)(ReferenceParm)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0244(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FEventReply                            CallFunc_Handled_ReturnValue_1;                    // 0x0248(0x00B8)()
	bool                                          CallFunc_EqualEqual_KeyKey_ReturnValue_1;          // 0x0300(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_ChatWidget_C_OnKeyDown) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_OnKeyDown");
static_assert(sizeof(UMG_ChatWidget_C_OnKeyDown) == 0x000308, "Wrong size on UMG_ChatWidget_C_OnKeyDown");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, MyGeometry) == 0x000000, "Member 'UMG_ChatWidget_C_OnKeyDown::MyGeometry' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, InKeyEvent) == 0x000038, "Member 'UMG_ChatWidget_C_OnKeyDown::InKeyEvent' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, ReturnValue) == 0x000070, "Member 'UMG_ChatWidget_C_OnKeyDown::ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, LocalKey) == 0x000128, "Member 'UMG_ChatWidget_C_OnKeyDown::LocalKey' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_GetKey_ReturnValue) == 0x000140, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_GetKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, Temp_int_Variable) == 0x000158, "Member 'UMG_ChatWidget_C_OnKeyDown::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_Handled_ReturnValue) == 0x000160, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue) == 0x000218, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_GetEngineSubsystem_ReturnValue) == 0x000220, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_GetEngineSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_Array_Length_ReturnValue) == 0x000228, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_GetKeysOfInput_ReturnValue) == 0x000230, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_GetKeysOfInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_Add_IntInt_ReturnValue) == 0x000240, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_Percent_IntInt_ReturnValue) == 0x000244, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_Handled_ReturnValue_1) == 0x000248, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_Handled_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_OnKeyDown, CallFunc_EqualEqual_KeyKey_ReturnValue_1) == 0x000300, "Member 'UMG_ChatWidget_C_OnKeyDown::CallFunc_EqualEqual_KeyKey_ReturnValue_1' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.Update Current Chat Room
// 0x0058 (0x0058 - 0x0000)
struct UMG_ChatWidget_C_Update_Current_Chat_Room final
{
public:
	struct FPBChatRoomStyle                       CallFunc_Map_Find_Value;                           // 0x0000(0x0028)()
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0030(0x0028)()
};
static_assert(alignof(UMG_ChatWidget_C_Update_Current_Chat_Room) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_Update_Current_Chat_Room");
static_assert(sizeof(UMG_ChatWidget_C_Update_Current_Chat_Room) == 0x000058, "Wrong size on UMG_ChatWidget_C_Update_Current_Chat_Room");
static_assert(offsetof(UMG_ChatWidget_C_Update_Current_Chat_Room, CallFunc_Map_Find_Value) == 0x000000, "Member 'UMG_ChatWidget_C_Update_Current_Chat_Room::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_Update_Current_Chat_Room, CallFunc_Map_Find_ReturnValue) == 0x000028, "Member 'UMG_ChatWidget_C_Update_Current_Chat_Room::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_Update_Current_Chat_Room, K2Node_MakeStruct_SlateColor) == 0x000030, "Member 'UMG_ChatWidget_C_Update_Current_Chat_Room::K2Node_MakeStruct_SlateColor' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.SendMessage
// 0x00B8 (0x00B8 - 0x0000)
struct UMG_ChatWidget_C_SendMessage final
{
public:
	bool                                          bWasSuccessful;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPBChatMessage                         NewMessage;                                        // 0x0008(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class UUMG_ChatMessageInfo_Widget_C*          LocalMessageInfo;                                  // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMG_ChatMessageInfo_Widget_C*          CallFunc_Create_ReturnValue;                       // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0050(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0060(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0068(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x0078(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FPBChatRoomStyle                       CallFunc_Map_Find_Value;                           // 0x0080(0x0028)()
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_SendMessage) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_SendMessage");
static_assert(sizeof(UMG_ChatWidget_C_SendMessage) == 0x0000B8, "Wrong size on UMG_ChatWidget_C_SendMessage");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, bWasSuccessful) == 0x000000, "Member 'UMG_ChatWidget_C_SendMessage::bWasSuccessful' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, NewMessage) == 0x000008, "Member 'UMG_ChatWidget_C_SendMessage::NewMessage' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, LocalMessageInfo) == 0x000040, "Member 'UMG_ChatWidget_C_SendMessage::LocalMessageInfo' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, CallFunc_Create_ReturnValue) == 0x000048, "Member 'UMG_ChatWidget_C_SendMessage::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, K2Node_CreateDelegate_OutputDelegate) == 0x000050, "Member 'UMG_ChatWidget_C_SendMessage::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000060, "Member 'UMG_ChatWidget_C_SendMessage::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, K2Node_CreateDelegate_OutputDelegate_1) == 0x000068, "Member 'UMG_ChatWidget_C_SendMessage::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x000078, "Member 'UMG_ChatWidget_C_SendMessage::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, CallFunc_Map_Find_Value) == 0x000080, "Member 'UMG_ChatWidget_C_SendMessage::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, CallFunc_Map_Find_ReturnValue) == 0x0000A8, "Member 'UMG_ChatWidget_C_SendMessage::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SendMessage, CallFunc_AddChild_ReturnValue) == 0x0000B0, "Member 'UMG_ChatWidget_C_SendMessage::CallFunc_AddChild_ReturnValue' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.ReceiveMessage
// 0x0080 (0x0080 - 0x0000)
struct UMG_ChatWidget_C_ReceiveMessage final
{
public:
	struct FPBChatMessage                         NewMessage;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class UUMG_ChatMessageInfo_Widget_C*          LocalMessageInfo;                                  // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPBChatRoomStyle                       CallFunc_Map_Find_Value;                           // 0x0048(0x0028)()
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMG_ChatMessageInfo_Widget_C*          CallFunc_Create_ReturnValue;                       // 0x0078(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_ReceiveMessage) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_ReceiveMessage");
static_assert(sizeof(UMG_ChatWidget_C_ReceiveMessage) == 0x000080, "Wrong size on UMG_ChatWidget_C_ReceiveMessage");
static_assert(offsetof(UMG_ChatWidget_C_ReceiveMessage, NewMessage) == 0x000000, "Member 'UMG_ChatWidget_C_ReceiveMessage::NewMessage' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ReceiveMessage, LocalMessageInfo) == 0x000038, "Member 'UMG_ChatWidget_C_ReceiveMessage::LocalMessageInfo' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ReceiveMessage, CallFunc_AddChild_ReturnValue) == 0x000040, "Member 'UMG_ChatWidget_C_ReceiveMessage::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ReceiveMessage, CallFunc_Map_Find_Value) == 0x000048, "Member 'UMG_ChatWidget_C_ReceiveMessage::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ReceiveMessage, CallFunc_Map_Find_ReturnValue) == 0x000070, "Member 'UMG_ChatWidget_C_ReceiveMessage::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ReceiveMessage, CallFunc_Create_ReturnValue) == 0x000078, "Member 'UMG_ChatWidget_C_ReceiveMessage::CallFunc_Create_ReturnValue' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.RefreshSavedMessage
// 0x00E0 (0x00E0 - 0x0000)
struct UMG_ChatWidget_C_RefreshSavedMessage final
{
public:
	TArray<struct FPBChatMessage>                 InSavedMessages;                                   // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class UUMG_ChatMessageInfo_Widget_C*          LocalMessageInfo;                                  // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPBChatMessage                         LocalMessage;                                      // 0x0018(0x0038)(Edit, BlueprintVisible)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPBChatMessage                         CallFunc_Array_Get_Item;                           // 0x0060(0x0038)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMG_ChatMessageInfo_Widget_C*          CallFunc_Create_ReturnValue;                       // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPBChatRoomStyle                       CallFunc_Map_Find_Value;                           // 0x00A8(0x0028)()
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_RefreshSavedMessage) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_RefreshSavedMessage");
static_assert(sizeof(UMG_ChatWidget_C_RefreshSavedMessage) == 0x0000E0, "Wrong size on UMG_ChatWidget_C_RefreshSavedMessage");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, InSavedMessages) == 0x000000, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::InSavedMessages' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, LocalMessageInfo) == 0x000010, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::LocalMessageInfo' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, LocalMessage) == 0x000018, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::LocalMessage' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, CallFunc_Array_Length_ReturnValue) == 0x000050, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, Temp_int_Array_Index_Variable) == 0x000054, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, Temp_int_Loop_Counter_Variable) == 0x000058, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, CallFunc_Array_Get_Item) == 0x000060, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, CallFunc_Less_IntInt_ReturnValue) == 0x000098, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, CallFunc_Add_IntInt_ReturnValue) == 0x00009C, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, CallFunc_Create_ReturnValue) == 0x0000A0, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, CallFunc_Map_Find_Value) == 0x0000A8, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, CallFunc_Map_Find_ReturnValue) == 0x0000D0, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshSavedMessage, CallFunc_AddChild_ReturnValue) == 0x0000D8, "Member 'UMG_ChatWidget_C_RefreshSavedMessage::CallFunc_AddChild_ReturnValue' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.ShowChatPanel
// 0x0030 (0x0030 - 0x0000)
struct UMG_ChatWidget_C_ShowChatPanel final
{
public:
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0020(0x0008)(NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_ShowChatPanel) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_ShowChatPanel");
static_assert(sizeof(UMG_ChatWidget_C_ShowChatPanel) == 0x000030, "Wrong size on UMG_ChatWidget_C_ShowChatPanel");
static_assert(offsetof(UMG_ChatWidget_C_ShowChatPanel, CallFunc_GetPlayerController_ReturnValue) == 0x000000, "Member 'UMG_ChatWidget_C_ShowChatPanel::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ShowChatPanel, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'UMG_ChatWidget_C_ShowChatPanel::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ShowChatPanel, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'UMG_ChatWidget_C_ShowChatPanel::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ShowChatPanel, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000020, "Member 'UMG_ChatWidget_C_ShowChatPanel::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_ShowChatPanel, CallFunc_GetPlayerController_ReturnValue_1) == 0x000028, "Member 'UMG_ChatWidget_C_ShowChatPanel::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.HiddenChatPanel
// 0x0028 (0x0028 - 0x0000)
struct UMG_ChatWidget_C_HiddenChatPanel final
{
public:
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMainMenu_IsMainMenu;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_HiddenChatPanel) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_HiddenChatPanel");
static_assert(sizeof(UMG_ChatWidget_C_HiddenChatPanel) == 0x000028, "Wrong size on UMG_ChatWidget_C_HiddenChatPanel");
static_assert(offsetof(UMG_ChatWidget_C_HiddenChatPanel, CallFunc_Not_PreBool_ReturnValue) == 0x000000, "Member 'UMG_ChatWidget_C_HiddenChatPanel::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_HiddenChatPanel, CallFunc_BooleanOR_ReturnValue) == 0x000001, "Member 'UMG_ChatWidget_C_HiddenChatPanel::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_HiddenChatPanel, CallFunc_IsMainMenu_IsMainMenu) == 0x000002, "Member 'UMG_ChatWidget_C_HiddenChatPanel::CallFunc_IsMainMenu_IsMainMenu' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_HiddenChatPanel, CallFunc_GetPlayerController_ReturnValue) == 0x000008, "Member 'UMG_ChatWidget_C_HiddenChatPanel::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_HiddenChatPanel, CallFunc_GetPlayerController_ReturnValue_1) == 0x000010, "Member 'UMG_ChatWidget_C_HiddenChatPanel::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_HiddenChatPanel, CallFunc_PlayAnimationReverse_ReturnValue) == 0x000018, "Member 'UMG_ChatWidget_C_HiddenChatPanel::CallFunc_PlayAnimationReverse_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_HiddenChatPanel, CallFunc_GetPlayerController_ReturnValue_2) == 0x000020, "Member 'UMG_ChatWidget_C_HiddenChatPanel::CallFunc_GetPlayerController_ReturnValue_2' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.InitSwitchChatRoomHintText
// 0x00C0 (0x00C0 - 0x0000)
struct UMG_ChatWidget_C_InitSwitchChatRoomHintText final
{
public:
	class UPBOptions*                             CallFunc_GetEngineSubsystem_ReturnValue;           // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EInputDevice                                  CallFunc_GetCurrentActivateInputDevice_ReturnValue; // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FKey>                           CallFunc_GetKeysOfInput_ReturnValue;               // 0x0010(0x0010)(ReferenceParm)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Key_GetDisplayName_ReturnValue;           // 0x0028(0x0018)()
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0040(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0058(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0098(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00A8(0x0018)()
};
static_assert(alignof(UMG_ChatWidget_C_InitSwitchChatRoomHintText) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_InitSwitchChatRoomHintText");
static_assert(sizeof(UMG_ChatWidget_C_InitSwitchChatRoomHintText) == 0x0000C0, "Wrong size on UMG_ChatWidget_C_InitSwitchChatRoomHintText");
static_assert(offsetof(UMG_ChatWidget_C_InitSwitchChatRoomHintText, CallFunc_GetEngineSubsystem_ReturnValue) == 0x000000, "Member 'UMG_ChatWidget_C_InitSwitchChatRoomHintText::CallFunc_GetEngineSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitSwitchChatRoomHintText, CallFunc_GetCurrentActivateInputDevice_ReturnValue) == 0x000008, "Member 'UMG_ChatWidget_C_InitSwitchChatRoomHintText::CallFunc_GetCurrentActivateInputDevice_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitSwitchChatRoomHintText, CallFunc_GetKeysOfInput_ReturnValue) == 0x000010, "Member 'UMG_ChatWidget_C_InitSwitchChatRoomHintText::CallFunc_GetKeysOfInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitSwitchChatRoomHintText, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000020, "Member 'UMG_ChatWidget_C_InitSwitchChatRoomHintText::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitSwitchChatRoomHintText, CallFunc_Key_GetDisplayName_ReturnValue) == 0x000028, "Member 'UMG_ChatWidget_C_InitSwitchChatRoomHintText::CallFunc_Key_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitSwitchChatRoomHintText, CallFunc_TextToUpper_ReturnValue) == 0x000040, "Member 'UMG_ChatWidget_C_InitSwitchChatRoomHintText::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitSwitchChatRoomHintText, K2Node_MakeStruct_FormatArgumentData) == 0x000058, "Member 'UMG_ChatWidget_C_InitSwitchChatRoomHintText::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitSwitchChatRoomHintText, K2Node_MakeArray_Array) == 0x000098, "Member 'UMG_ChatWidget_C_InitSwitchChatRoomHintText::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitSwitchChatRoomHintText, CallFunc_Format_ReturnValue) == 0x0000A8, "Member 'UMG_ChatWidget_C_InitSwitchChatRoomHintText::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.InitAwakeChatPanelText
// 0x00C0 (0x00C0 - 0x0000)
struct UMG_ChatWidget_C_InitAwakeChatPanelText final
{
public:
	class UPBOptions*                             CallFunc_GetEngineSubsystem_ReturnValue;           // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EInputDevice                                  CallFunc_GetCurrentActivateInputDevice_ReturnValue; // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FKey>                           CallFunc_GetKeysOfInput_ReturnValue;               // 0x0010(0x0010)(ReferenceParm)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Key_GetDisplayName_ReturnValue;           // 0x0028(0x0018)()
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0040(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0058(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0098(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00A8(0x0018)()
};
static_assert(alignof(UMG_ChatWidget_C_InitAwakeChatPanelText) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_InitAwakeChatPanelText");
static_assert(sizeof(UMG_ChatWidget_C_InitAwakeChatPanelText) == 0x0000C0, "Wrong size on UMG_ChatWidget_C_InitAwakeChatPanelText");
static_assert(offsetof(UMG_ChatWidget_C_InitAwakeChatPanelText, CallFunc_GetEngineSubsystem_ReturnValue) == 0x000000, "Member 'UMG_ChatWidget_C_InitAwakeChatPanelText::CallFunc_GetEngineSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitAwakeChatPanelText, CallFunc_GetCurrentActivateInputDevice_ReturnValue) == 0x000008, "Member 'UMG_ChatWidget_C_InitAwakeChatPanelText::CallFunc_GetCurrentActivateInputDevice_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitAwakeChatPanelText, CallFunc_GetKeysOfInput_ReturnValue) == 0x000010, "Member 'UMG_ChatWidget_C_InitAwakeChatPanelText::CallFunc_GetKeysOfInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitAwakeChatPanelText, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000020, "Member 'UMG_ChatWidget_C_InitAwakeChatPanelText::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitAwakeChatPanelText, CallFunc_Key_GetDisplayName_ReturnValue) == 0x000028, "Member 'UMG_ChatWidget_C_InitAwakeChatPanelText::CallFunc_Key_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitAwakeChatPanelText, CallFunc_TextToUpper_ReturnValue) == 0x000040, "Member 'UMG_ChatWidget_C_InitAwakeChatPanelText::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitAwakeChatPanelText, K2Node_MakeStruct_FormatArgumentData) == 0x000058, "Member 'UMG_ChatWidget_C_InitAwakeChatPanelText::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitAwakeChatPanelText, K2Node_MakeArray_Array) == 0x000098, "Member 'UMG_ChatWidget_C_InitAwakeChatPanelText::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_InitAwakeChatPanelText, CallFunc_Format_ReturnValue) == 0x0000A8, "Member 'UMG_ChatWidget_C_InitAwakeChatPanelText::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.SetDelayHideMessageTimer
// 0x0018 (0x0018 - 0x0000)
struct UMG_ChatWidget_C_SetDelayHideMessageTimer final
{
public:
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0000(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0010(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_SetDelayHideMessageTimer) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_SetDelayHideMessageTimer");
static_assert(sizeof(UMG_ChatWidget_C_SetDelayHideMessageTimer) == 0x000018, "Wrong size on UMG_ChatWidget_C_SetDelayHideMessageTimer");
static_assert(offsetof(UMG_ChatWidget_C_SetDelayHideMessageTimer, K2Node_CreateDelegate_OutputDelegate) == 0x000000, "Member 'UMG_ChatWidget_C_SetDelayHideMessageTimer::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_SetDelayHideMessageTimer, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000010, "Member 'UMG_ChatWidget_C_SetDelayHideMessageTimer::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.ShowMinMessage
// 0x0008 (0x0008 - 0x0000)
struct UMG_ChatWidget_C_ShowMinMessage final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_ShowMinMessage) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_ShowMinMessage");
static_assert(sizeof(UMG_ChatWidget_C_ShowMinMessage) == 0x000008, "Wrong size on UMG_ChatWidget_C_ShowMinMessage");
static_assert(offsetof(UMG_ChatWidget_C_ShowMinMessage, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'UMG_ChatWidget_C_ShowMinMessage::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.IsMainMenu
// 0x0020 (0x0020 - 0x0000)
struct UMG_ChatWidget_C_IsMainMenu final
{
public:
	bool                                          IsMainMenu_0;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APBGameMode_Menu*                       K2Node_DynamicCast_AsPBGame_Mode_Menu;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_ChatWidget_C_IsMainMenu) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_IsMainMenu");
static_assert(sizeof(UMG_ChatWidget_C_IsMainMenu) == 0x000020, "Wrong size on UMG_ChatWidget_C_IsMainMenu");
static_assert(offsetof(UMG_ChatWidget_C_IsMainMenu, IsMainMenu_0) == 0x000000, "Member 'UMG_ChatWidget_C_IsMainMenu::IsMainMenu_0' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_IsMainMenu, CallFunc_GetGameMode_ReturnValue) == 0x000008, "Member 'UMG_ChatWidget_C_IsMainMenu::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_IsMainMenu, K2Node_DynamicCast_AsPBGame_Mode_Menu) == 0x000010, "Member 'UMG_ChatWidget_C_IsMainMenu::K2Node_DynamicCast_AsPBGame_Mode_Menu' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_IsMainMenu, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'UMG_ChatWidget_C_IsMainMenu::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.CommitMessage
// 0x0018 (0x0018 - 0x0000)
struct UMG_ChatWidget_C_CommitMessage final
{
public:
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0000(0x0018)()
};
static_assert(alignof(UMG_ChatWidget_C_CommitMessage) == 0x000008, "Wrong alignment on UMG_ChatWidget_C_CommitMessage");
static_assert(sizeof(UMG_ChatWidget_C_CommitMessage) == 0x000018, "Wrong size on UMG_ChatWidget_C_CommitMessage");
static_assert(offsetof(UMG_ChatWidget_C_CommitMessage, CallFunc_GetText_ReturnValue) == 0x000000, "Member 'UMG_ChatWidget_C_CommitMessage::CallFunc_GetText_ReturnValue' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.OnBackPreviousEvent
// 0x0001 (0x0001 - 0x0000)
struct UMG_ChatWidget_C_OnBackPreviousEvent final
{
public:
	bool                                          bQuitgame;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_ChatWidget_C_OnBackPreviousEvent) == 0x000001, "Wrong alignment on UMG_ChatWidget_C_OnBackPreviousEvent");
static_assert(sizeof(UMG_ChatWidget_C_OnBackPreviousEvent) == 0x000001, "Wrong size on UMG_ChatWidget_C_OnBackPreviousEvent");
static_assert(offsetof(UMG_ChatWidget_C_OnBackPreviousEvent, bQuitgame) == 0x000000, "Member 'UMG_ChatWidget_C_OnBackPreviousEvent::bQuitgame' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.OnSavePageEvent
// 0x0008 (0x0008 - 0x0000)
struct UMG_ChatWidget_C_OnSavePageEvent final
{
public:
	class FName                                   PageName;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_ChatWidget_C_OnSavePageEvent) == 0x000004, "Wrong alignment on UMG_ChatWidget_C_OnSavePageEvent");
static_assert(sizeof(UMG_ChatWidget_C_OnSavePageEvent) == 0x000008, "Wrong size on UMG_ChatWidget_C_OnSavePageEvent");
static_assert(offsetof(UMG_ChatWidget_C_OnSavePageEvent, PageName) == 0x000000, "Member 'UMG_ChatWidget_C_OnSavePageEvent::PageName' has a wrong offset!");

// Function UMG_ChatWidget.UMG_ChatWidget_C.RefreshVisibility
// 0x0003 (0x0003 - 0x0000)
struct UMG_ChatWidget_C_RefreshVisibility final
{
public:
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue_1;        // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_ChatWidget_C_RefreshVisibility) == 0x000001, "Wrong alignment on UMG_ChatWidget_C_RefreshVisibility");
static_assert(sizeof(UMG_ChatWidget_C_RefreshVisibility) == 0x000003, "Wrong size on UMG_ChatWidget_C_RefreshVisibility");
static_assert(offsetof(UMG_ChatWidget_C_RefreshVisibility, CallFunc_EqualEqual_NameName_ReturnValue) == 0x000000, "Member 'UMG_ChatWidget_C_RefreshVisibility::CallFunc_EqualEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshVisibility, CallFunc_EqualEqual_NameName_ReturnValue_1) == 0x000001, "Member 'UMG_ChatWidget_C_RefreshVisibility::CallFunc_EqualEqual_NameName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_ChatWidget_C_RefreshVisibility, CallFunc_BooleanOR_ReturnValue) == 0x000002, "Member 'UMG_ChatWidget_C_RefreshVisibility::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

}

