#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_SingleMedal

#include "Basic.hpp"

#include "UMG_SingleMedal_classes.hpp"
#include "UMG_SingleMedal_parameters.hpp"


namespace SDK
{

// Function UMG_SingleMedal.UMG_SingleMedal_C.ExecuteUbergraph_UMG_SingleMedal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_SingleMedal_C::ExecuteUbergraph_UMG_SingleMedal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SingleMedal_C", "ExecuteUbergraph_UMG_SingleMedal");

	Params::UMG_SingleMedal_C_ExecuteUbergraph_UMG_SingleMedal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_SingleMedal.UMG_SingleMedal_C.SetCustomFocus
// (BlueprintCallable, BlueprintEvent)

void UUMG_SingleMedal_C::SetCustomFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SingleMedal_C", "SetCustomFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_SingleMedal.UMG_SingleMedal_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UUMG_SingleMedal_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SingleMedal_C", "OnRemovedFromFocusPath");

	Params::UMG_SingleMedal_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_SingleMedal.UMG_SingleMedal_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UUMG_SingleMedal_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SingleMedal_C", "OnAddedToFocusPath");

	Params::UMG_SingleMedal_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_SingleMedal.UMG_SingleMedal_C.BndEvt__MainButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUMG_SingleMedal_C::BndEvt__MainButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SingleMedal_C", "BndEvt__MainButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_SingleMedal.UMG_SingleMedal_C.SetInfo
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             InMedalID                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InCount                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InSerialNumber                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FFPB_MedalDetailsConfig_BP       InMedalDetailsConfig                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)

void UUMG_SingleMedal_C::SetInfo(class FName InMedalID, int32 InCount, int32 InSerialNumber, struct FFPB_MedalDetailsConfig_BP& InMedalDetailsConfig)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SingleMedal_C", "SetInfo");

	Params::UMG_SingleMedal_C_SetInfo Parms{};

	Parms.InMedalID = InMedalID;
	Parms.InCount = InCount;
	Parms.InSerialNumber = InSerialNumber;
	Parms.InMedalDetailsConfig = std::move(InMedalDetailsConfig);

	UObject::ProcessEvent(Func, &Parms);

	InMedalDetailsConfig = std::move(Parms.InMedalDetailsConfig);
}


// Function UMG_SingleMedal.UMG_SingleMedal_C.SetNewItemInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUMG_SingleMedal_C::SetNewItemInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SingleMedal_C", "SetNewItemInfo");

	UObject::ProcessEvent(Func, nullptr);
}

}

