#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_HelmetHUD_DashHint

#include "Basic.hpp"

#include "UMG_HelmetHUD_DashHint_classes.hpp"
#include "UMG_HelmetHUD_DashHint_parameters.hpp"


namespace SDK
{

// Function UMG_HelmetHUD_DashHint.UMG_HelmetHUD_DashHint_C.ExecuteUbergraph_UMG_HelmetHUD_DashHint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_HelmetHUD_DashHint_C::ExecuteUbergraph_UMG_HelmetHUD_DashHint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_HelmetHUD_DashHint_C", "ExecuteUbergraph_UMG_HelmetHUD_DashHint");

	Params::UMG_HelmetHUD_DashHint_C_ExecuteUbergraph_UMG_HelmetHUD_DashHint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_HelmetHUD_DashHint.UMG_HelmetHUD_DashHint_C.K2_RefreshUseTimesInfo
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsMinus                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_HelmetHUD_DashHint_C::K2_RefreshUseTimesInfo(bool bIsMinus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_HelmetHUD_DashHint_C", "K2_RefreshUseTimesInfo");

	Params::UMG_HelmetHUD_DashHint_C_K2_RefreshUseTimesInfo Parms{};

	Parms.bIsMinus = bIsMinus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_HelmetHUD_DashHint.UMG_HelmetHUD_DashHint_C.RefreshUseTimesInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsMinus                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_HelmetHUD_DashHint_C::RefreshUseTimesInfo(bool bIsMinus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_HelmetHUD_DashHint_C", "RefreshUseTimesInfo");

	Params::UMG_HelmetHUD_DashHint_C_RefreshUseTimesInfo Parms{};

	Parms.bIsMinus = bIsMinus;

	UObject::ProcessEvent(Func, &Parms);
}

}

