#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: APBSmokeGrenade_BP_squid

#include "Basic.hpp"

#include "APBSmokeGrenade_BP_squid_classes.hpp"
#include "APBSmokeGrenade_BP_squid_parameters.hpp"


namespace SDK
{

// Function APBSmokeGrenade_BP_squid.APBSmokeGrenade_BP_squid_C.ExecuteUbergraph_APBSmokeGrenade_BP_squid
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAPBSmokeGrenade_BP_squid_C::ExecuteUbergraph_APBSmokeGrenade_BP_squid(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("APBSmokeGrenade_BP_squid_C", "ExecuteUbergraph_APBSmokeGrenade_BP_squid");

	Params::APBSmokeGrenade_BP_squid_C_ExecuteUbergraph_APBSmokeGrenade_BP_squid Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function APBSmokeGrenade_BP_squid.APBSmokeGrenade_BP_squid_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAPBSmokeGrenade_BP_squid_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("APBSmokeGrenade_BP_squid_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function APBSmokeGrenade_BP_squid.APBSmokeGrenade_BP_squid_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAPBSmokeGrenade_BP_squid_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("APBSmokeGrenade_BP_squid_C", "ReceiveTick");

	Params::APBSmokeGrenade_BP_squid_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function APBSmokeGrenade_BP_squid.APBSmokeGrenade_BP_squid_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AAPBSmokeGrenade_BP_squid_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("APBSmokeGrenade_BP_squid_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

