#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CatchingModule_BP_NoCD

#include "Basic.hpp"

#include "CatchingModule_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CatchingModule_BP_NoCD.BP_CatchingModule_BP_NoCD_C
// 0x0000 (0x0528 - 0x0528)
class ABP_CatchingModule_BP_NoCD_C final : public ACatchingModule_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CatchingModule_BP_NoCD_C">();
	}
	static class ABP_CatchingModule_BP_NoCD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CatchingModule_BP_NoCD_C>();
	}
};
static_assert(alignof(ABP_CatchingModule_BP_NoCD_C) == 0x000008, "Wrong alignment on ABP_CatchingModule_BP_NoCD_C");
static_assert(sizeof(ABP_CatchingModule_BP_NoCD_C) == 0x000528, "Wrong size on ABP_CatchingModule_BP_NoCD_C");

}

