#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Option_FloatConfigurableOption

#include "Basic.hpp"

#include "ProjectBoundary_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Option_FloatConfigurableOption.BP_Option_FloatConfigurableOption_C
// 0x0000 (0x00C0 - 0x00C0)
class UBP_Option_FloatConfigurableOption_C final : public UPBFloatSettingOption
{
public:
	void ModifyConfigurability();
	void ShouldBeConfigurable(bool* IsConfigurable);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Option_FloatConfigurableOption_C">();
	}
	static class UBP_Option_FloatConfigurableOption_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Option_FloatConfigurableOption_C>();
	}
};
static_assert(alignof(UBP_Option_FloatConfigurableOption_C) == 0x000008, "Wrong alignment on UBP_Option_FloatConfigurableOption_C");
static_assert(sizeof(UBP_Option_FloatConfigurableOption_C) == 0x0000C0, "Wrong size on UBP_Option_FloatConfigurableOption_C");

}

