#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Option_BoolGraphicsSettingBase

#include "Basic.hpp"

#include "ProjectBoundary_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Option_BoolGraphicsSettingBase.BP_Option_BoolGraphicsSettingBase_C
// 0x0000 (0x00B8 - 0x00B8)
class UBP_Option_BoolGraphicsSettingBase_C : public UPBBoolSettingOption
{
public:
	void ModifyViaDependencies(bool IsDependencyChanged);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Option_BoolGraphicsSettingBase_C">();
	}
	static class UBP_Option_BoolGraphicsSettingBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Option_BoolGraphicsSettingBase_C>();
	}
};
static_assert(alignof(UBP_Option_BoolGraphicsSettingBase_C) == 0x000008, "Wrong alignment on UBP_Option_BoolGraphicsSettingBase_C");
static_assert(sizeof(UBP_Option_BoolGraphicsSettingBase_C) == 0x0000B8, "Wrong size on UBP_Option_BoolGraphicsSettingBase_C");

}

