#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PBAIController

#include "Basic.hpp"

#include "ProjectBoundary_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PBAIController.BP_PBAIController_C
// 0x0008 (0x04E8 - 0x04E0)
class ABP_PBAIController_C final : public APBAIController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_PBAIController(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PBAIController_C">();
	}
	static class ABP_PBAIController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PBAIController_C>();
	}
};
static_assert(alignof(ABP_PBAIController_C) == 0x000008, "Wrong alignment on ABP_PBAIController_C");
static_assert(sizeof(ABP_PBAIController_C) == 0x0004E8, "Wrong size on ABP_PBAIController_C");
static_assert(offsetof(ABP_PBAIController_C, UberGraphFrame) == 0x0004E0, "Member 'ABP_PBAIController_C::UberGraphFrame' has a wrong offset!");

}

