#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PBDamageIndicatorComponent

#include "Basic.hpp"

#include "BP_PBDamageIndicatorComponent_classes.hpp"
#include "BP_PBDamageIndicatorComponent_parameters.hpp"


namespace SDK
{

// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.ExecuteUbergraph_BP_PBDamageIndicatorComponent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PBDamageIndicatorComponent_C::ExecuteUbergraph_BP_PBDamageIndicatorComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "ExecuteUbergraph_BP_PBDamageIndicatorComponent");

	Params::BP_PBDamageIndicatorComponent_C_ExecuteUbergraph_BP_PBDamageIndicatorComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.ReceiveEndPlay
// (Event, Public, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PBDamageIndicatorComponent_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "ReceiveEndPlay");

	Params::BP_PBDamageIndicatorComponent_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.ShowDamageIndicator
// (BlueprintCallable, BlueprintEvent)

void UBP_PBDamageIndicatorComponent_C::ShowDamageIndicator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "ShowDamageIndicator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.FadeDamageIndicator
// (BlueprintCallable, BlueprintEvent)

void UBP_PBDamageIndicatorComponent_C::FadeDamageIndicator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "FadeDamageIndicator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PBDamageIndicatorComponent_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "ReceiveTick");

	Params::BP_PBDamageIndicatorComponent_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_PBDamageIndicatorComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.BeHit
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            Pawn                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsBackPack                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsRadialDamage                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FVector                          RadialDamageSourceLocation                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PBDamageIndicatorComponent_C::BeHit(class APawn* Pawn, float Damage, bool IsBackPack, bool IsRadialDamage, const struct FVector& RadialDamageSourceLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "BeHit");

	Params::BP_PBDamageIndicatorComponent_C_BeHit Parms{};

	Parms.Pawn = Pawn;
	Parms.Damage = Damage;
	Parms.IsBackPack = IsBackPack;
	Parms.IsRadialDamage = IsRadialDamage;
	Parms.RadialDamageSourceLocation = std::move(RadialDamageSourceLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.CalDamageAccumlationPerPlayer
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InDeltaSeconds                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APawn*                            PawnRef                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PBDamageIndicatorComponent_C::CalDamageAccumlationPerPlayer(float InDeltaSeconds, class APawn* PawnRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "CalDamageAccumlationPerPlayer");

	Params::BP_PBDamageIndicatorComponent_C_CalDamageAccumlationPerPlayer Parms{};

	Parms.InDeltaSeconds = InDeltaSeconds;
	Parms.PawnRef = PawnRef;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.InitializeScreenDamageFX
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_PBDamageIndicatorComponent_C::InitializeScreenDamageFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "InitializeScreenDamageFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.AddScreenDamageFX
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Damage_Instigator_Location                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          RadialDamageSourceLocation                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsRadialDamage                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PBDamageIndicatorComponent_C::AddScreenDamageFX(const struct FVector& Damage_Instigator_Location, const struct FVector& RadialDamageSourceLocation, bool bIsRadialDamage, float Damage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "AddScreenDamageFX");

	Params::BP_PBDamageIndicatorComponent_C_AddScreenDamageFX Parms{};

	Parms.Damage_Instigator_Location = std::move(Damage_Instigator_Location);
	Parms.RadialDamageSourceLocation = std::move(RadialDamageSourceLocation);
	Parms.bIsRadialDamage = bIsRadialDamage;
	Parms.Damage = Damage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.FadeScreenDamageOverTime
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Delta_Seconds                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PBDamageIndicatorComponent_C::FadeScreenDamageOverTime(float Delta_Seconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "FadeScreenDamageOverTime");

	Params::BP_PBDamageIndicatorComponent_C_FadeScreenDamageOverTime Parms{};

	Parms.Delta_Seconds = Delta_Seconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.ClearScreenDamageFX
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_PBDamageIndicatorComponent_C::ClearScreenDamageFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "ClearScreenDamageFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.UpdateHealingInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsHealing_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_PBDamageIndicatorComponent_C::UpdateHealingInfo(bool bIsHealing_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "UpdateHealingInfo");

	Params::BP_PBDamageIndicatorComponent_C_UpdateHealingInfo Parms{};

	Parms.bIsHealing_0 = bIsHealing_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.DisplayArmorBreakFX
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsArmorBroken                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_PBDamageIndicatorComponent_C::DisplayArmorBreakFX(bool bIsArmorBroken)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "DisplayArmorBreakFX");

	Params::BP_PBDamageIndicatorComponent_C_DisplayArmorBreakFX Parms{};

	Parms.bIsArmorBroken = bIsArmorBroken;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.ClearScreenArmorBreakFX
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_PBDamageIndicatorComponent_C::ClearScreenArmorBreakFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "ClearScreenArmorBreakFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.ClearAllScreenFX
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_PBDamageIndicatorComponent_C::ClearAllScreenFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "ClearAllScreenFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.PlayArmorBreakShake
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsArmorBroken                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_PBDamageIndicatorComponent_C::PlayArmorBreakShake(bool bIsArmorBroken)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "PlayArmorBreakShake");

	Params::BP_PBDamageIndicatorComponent_C_PlayArmorBreakShake Parms{};

	Parms.bIsArmorBroken = bIsArmorBroken;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PBDamageIndicatorComponent.BP_PBDamageIndicatorComponent_C.PlayHitShake
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PBDamageIndicatorComponent_C::PlayHitShake(float Damage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PBDamageIndicatorComponent_C", "PlayHitShake");

	Params::BP_PBDamageIndicatorComponent_C_PlayHitShake Parms{};

	Parms.Damage = Damage;

	UObject::ProcessEvent(Func, &Parms);
}

}

