#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PBImpulseGrenadeLauncher_INF

#include "Basic.hpp"

#include "BP_PBImpulseGrenadeLauncher_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PBImpulseGrenadeLauncher_INF.BP_PBImpulseGrenadeLauncher_INF_C
// 0x0000 (0x0698 - 0x0698)
class ABP_PBImpulseGrenadeLauncher_INF_C final : public ABP_PBImpulseGrenadeLauncher_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PBImpulseGrenadeLauncher_INF_C">();
	}
	static class ABP_PBImpulseGrenadeLauncher_INF_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PBImpulseGrenadeLauncher_INF_C>();
	}
};
static_assert(alignof(ABP_PBImpulseGrenadeLauncher_INF_C) == 0x000008, "Wrong alignment on ABP_PBImpulseGrenadeLauncher_INF_C");
static_assert(sizeof(ABP_PBImpulseGrenadeLauncher_INF_C) == 0x000698, "Wrong size on ABP_PBImpulseGrenadeLauncher_INF_C");

}

