#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Option_SuperResolutionQuality

#include "Basic.hpp"

#include "Option_SuperResolutionQuality_classes.hpp"
#include "Option_SuperResolutionQuality_parameters.hpp"


namespace SDK
{

// Function Option_SuperResolutionQuality.Option_SuperResolutionQuality_C.ExecuteUbergraph_Option_SuperResolutionQuality
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOption_SuperResolutionQuality_C::ExecuteUbergraph_Option_SuperResolutionQuality(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Option_SuperResolutionQuality_C", "ExecuteUbergraph_Option_SuperResolutionQuality");

	Params::Option_SuperResolutionQuality_C_ExecuteUbergraph_Option_SuperResolutionQuality Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Option_SuperResolutionQuality.Option_SuperResolutionQuality_C.K2_Modify
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsDependencyChanged                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UOption_SuperResolutionQuality_C::K2_Modify(bool bIsDependencyChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Option_SuperResolutionQuality_C", "K2_Modify");

	Params::Option_SuperResolutionQuality_C_K2_Modify Parms{};

	Parms.bIsDependencyChanged = bIsDependencyChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Option_SuperResolutionQuality.Option_SuperResolutionQuality_C.K2_GetValueTitleArray
// (Event, Public, BlueprintEvent)

void UOption_SuperResolutionQuality_C::K2_GetValueTitleArray()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Option_SuperResolutionQuality_C", "K2_GetValueTitleArray");

	UObject::ProcessEvent(Func, nullptr);
}

}

