#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PB_GameInstance

#include "Basic.hpp"

#include "PB_GameInstance_classes.hpp"
#include "PB_GameInstance_parameters.hpp"


namespace SDK
{

// Function PB_GameInstance.PB_GameInstance_C.ExecuteUbergraph_PB_GameInstance
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPB_GameInstance_C::ExecuteUbergraph_PB_GameInstance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PB_GameInstance_C", "ExecuteUbergraph_PB_GameInstance");

	Params::PB_GameInstance_C_ExecuteUbergraph_PB_GameInstance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PB_GameInstance.PB_GameInstance_C.WaterMarkValidityCheck
// (BlueprintCallable, BlueprintEvent)

void UPB_GameInstance_C::WaterMarkValidityCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PB_GameInstance_C", "WaterMarkValidityCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PB_GameInstance.PB_GameInstance_C.ReceiveInit
// (Event, Public, BlueprintEvent)

void UPB_GameInstance_C::ReceiveInit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PB_GameInstance_C", "ReceiveInit");

	UObject::ProcessEvent(Func, nullptr);
}

}

