#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerHUD_BP

#include "Basic.hpp"

#include "PlayerHUD_BP_classes.hpp"
#include "PlayerHUD_BP_parameters.hpp"


namespace SDK
{

// Function PlayerHUD_BP.PlayerHUD_BP_C.ExecuteUbergraph_PlayerHUD_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlayerHUD_BP_C::ExecuteUbergraph_PlayerHUD_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "ExecuteUbergraph_PlayerHUD_BP");

	Params::PlayerHUD_BP_C_ExecuteUbergraph_PlayerHUD_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.K2_OnVoiceChatPlayerTalkingUpdated
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FString                           ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    bIsTalking                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APlayerHUD_BP_C::K2_OnVoiceChatPlayerTalkingUpdated(const class FString& ChannelName, const class FString& PlayerName, bool bIsTalking)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "K2_OnVoiceChatPlayerTalkingUpdated");

	Params::PlayerHUD_BP_C_K2_OnVoiceChatPlayerTalkingUpdated Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.PlayerName = std::move(PlayerName);
	Parms.bIsTalking = bIsTalking;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.K2_ReceiveMessage
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FPBMessageInfo                   InMessageInfo                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void APlayerHUD_BP_C::K2_ReceiveMessage(const struct FPBMessageInfo& InMessageInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "K2_ReceiveMessage");

	Params::PlayerHUD_BP_C_K2_ReceiveMessage Parms{};

	Parms.InMessageInfo = std::move(InMessageInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.K2_StopQuickRespawn
// (Event, Public, BlueprintEvent)

void APlayerHUD_BP_C::K2_StopQuickRespawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "K2_StopQuickRespawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.K2_StartQuickRespawn
// (Event, Public, BlueprintEvent)

void APlayerHUD_BP_C::K2_StartQuickRespawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "K2_StartQuickRespawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.K2_StopKillCamera
// (Event, Public, BlueprintEvent)

void APlayerHUD_BP_C::K2_StopKillCamera()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "K2_StopKillCamera");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.K2_StartKillCamera
// (Event, Public, BlueprintEvent)

void APlayerHUD_BP_C::K2_StartKillCamera()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "K2_StartKillCamera");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.K2_WaitingToRestart
// (Event, Public, BlueprintEvent)

void APlayerHUD_BP_C::K2_WaitingToRestart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "K2_WaitingToRestart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.NotifyPlayerEnter
// (Event, Public, BlueprintEvent)
// Parameters:
// class APBPlayerState*                   KillerPlayerState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bEnter                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APlayerHUD_BP_C::NotifyPlayerEnter(class APBPlayerState* KillerPlayerState, bool bEnter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "NotifyPlayerEnter");

	Params::PlayerHUD_BP_C_NotifyPlayerEnter Parms{};

	Parms.KillerPlayerState = KillerPlayerState;
	Parms.bEnter = bEnter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlayerHUD_BP_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "ReceiveEndPlay");

	Params::PlayerHUD_BP_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.NotifyBeKilled
// (Event, Public, BlueprintEvent)
// Parameters:
// class APBPlayerState*                   KillerPlayerState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APBPlayerState*                   KilledPlayerState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UDamageType*                      DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPBHitZone                              HitZone                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTextureRenderTarget2D*           InInstigatorRenderTarget                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture*                         InInstigatorTexture                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlayerHUD_BP_C::NotifyBeKilled(class APBPlayerState* KillerPlayerState, class APBPlayerState* KilledPlayerState, const class UDamageType* DamageType, EPBHitZone HitZone, const class UTextureRenderTarget2D* InInstigatorRenderTarget, const class UTexture* InInstigatorTexture, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "NotifyBeKilled");

	Params::PlayerHUD_BP_C_NotifyBeKilled Parms{};

	Parms.KillerPlayerState = KillerPlayerState;
	Parms.KilledPlayerState = KilledPlayerState;
	Parms.DamageType = DamageType;
	Parms.HitZone = HitZone;
	Parms.InInstigatorRenderTarget = InInstigatorRenderTarget;
	Parms.InInstigatorTexture = InInstigatorTexture;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APlayerHUD_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.RemoveWidgetOnEndPlay
// (Public, BlueprintCallable, BlueprintEvent)

void APlayerHUD_BP_C::RemoveWidgetOnEndPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "RemoveWidgetOnEndPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerHUD_BP.PlayerHUD_BP_C.UpdateKillInfoShowDemoWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APBPlayerState*                   KillerPlayerState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APBPlayerState*                   KilledPlayerState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlayerHUD_BP_C::UpdateKillInfoShowDemoWidget(class APBPlayerState* KillerPlayerState, class APBPlayerState* KilledPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerHUD_BP_C", "UpdateKillInfoShowDemoWidget");

	Params::PlayerHUD_BP_C_UpdateKillInfoShowDemoWidget Parms{};

	Parms.KillerPlayerState = KillerPlayerState;
	Parms.KilledPlayerState = KilledPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}

}

