#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PSXBaseHeatDetector_BP

#include "Basic.hpp"


namespace SDK::Params
{

// Function PSXBaseHeatDetector_BP.PSXBaseHeatDetector_BP_C.ExecuteUbergraph_PSXBaseHeatDetector_BP
// 0x0008 (0x0008 - 0x0000)
struct PSXBaseHeatDetector_BP_C_ExecuteUbergraph_PSXBaseHeatDetector_BP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PSXBaseHeatDetector_BP_C_ExecuteUbergraph_PSXBaseHeatDetector_BP) == 0x000004, "Wrong alignment on PSXBaseHeatDetector_BP_C_ExecuteUbergraph_PSXBaseHeatDetector_BP");
static_assert(sizeof(PSXBaseHeatDetector_BP_C_ExecuteUbergraph_PSXBaseHeatDetector_BP) == 0x000008, "Wrong size on PSXBaseHeatDetector_BP_C_ExecuteUbergraph_PSXBaseHeatDetector_BP");
static_assert(offsetof(PSXBaseHeatDetector_BP_C_ExecuteUbergraph_PSXBaseHeatDetector_BP, EntryPoint) == 0x000000, "Member 'PSXBaseHeatDetector_BP_C_ExecuteUbergraph_PSXBaseHeatDetector_BP::EntryPoint' has a wrong offset!");
static_assert(offsetof(PSXBaseHeatDetector_BP_C_ExecuteUbergraph_PSXBaseHeatDetector_BP, CallFunc_Greater_IntInt_ReturnValue) == 0x000004, "Member 'PSXBaseHeatDetector_BP_C_ExecuteUbergraph_PSXBaseHeatDetector_BP::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

}

