#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_DispChar_Map

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_DispChar_Map.UI_DispChar_Map_C.ExecuteUbergraph_UI_DispChar_Map
// 0x0004 (0x0004 - 0x0000)
struct UI_DispChar_Map_C_ExecuteUbergraph_UI_DispChar_Map final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_DispChar_Map_C_ExecuteUbergraph_UI_DispChar_Map) == 0x000004, "Wrong alignment on UI_DispChar_Map_C_ExecuteUbergraph_UI_DispChar_Map");
static_assert(sizeof(UI_DispChar_Map_C_ExecuteUbergraph_UI_DispChar_Map) == 0x000004, "Wrong size on UI_DispChar_Map_C_ExecuteUbergraph_UI_DispChar_Map");
static_assert(offsetof(UI_DispChar_Map_C_ExecuteUbergraph_UI_DispChar_Map, EntryPoint) == 0x000000, "Member 'UI_DispChar_Map_C_ExecuteUbergraph_UI_DispChar_Map::EntryPoint' has a wrong offset!");

}

