#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_MVPInfo

#include "Basic.hpp"


namespace SDK::Params
{

// Function UMG_MVPInfo.UMG_MVPInfo_C.ExecuteUbergraph_UMG_MVPInfo
// 0x0004 (0x0004 - 0x0000)
struct UMG_MVPInfo_C_ExecuteUbergraph_UMG_MVPInfo final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_MVPInfo_C_ExecuteUbergraph_UMG_MVPInfo) == 0x000004, "Wrong alignment on UMG_MVPInfo_C_ExecuteUbergraph_UMG_MVPInfo");
static_assert(sizeof(UMG_MVPInfo_C_ExecuteUbergraph_UMG_MVPInfo) == 0x000004, "Wrong size on UMG_MVPInfo_C_ExecuteUbergraph_UMG_MVPInfo");
static_assert(offsetof(UMG_MVPInfo_C_ExecuteUbergraph_UMG_MVPInfo, EntryPoint) == 0x000000, "Member 'UMG_MVPInfo_C_ExecuteUbergraph_UMG_MVPInfo::EntryPoint' has a wrong offset!");

}

