#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_InventorySlot

#include "Basic.hpp"

#include "UMG_InventorySlot_classes.hpp"
#include "UMG_InventorySlot_parameters.hpp"


namespace SDK
{

// Function UMG_InventorySlot.UMG_InventorySlot_C.ExecuteUbergraph_UMG_InventorySlot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_InventorySlot_C::ExecuteUbergraph_UMG_InventorySlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_InventorySlot_C", "ExecuteUbergraph_UMG_InventorySlot");

	Params::UMG_InventorySlot_C_ExecuteUbergraph_UMG_InventorySlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_InventorySlot.UMG_InventorySlot_C.K2_OnRefreshSlot
// (Event, Protected, BlueprintEvent)

void UUMG_InventorySlot_C::K2_OnRefreshSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_InventorySlot_C", "K2_OnRefreshSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_InventorySlot.UMG_InventorySlot_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_InventorySlot_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_InventorySlot_C", "PreConstruct");

	Params::UMG_InventorySlot_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_InventorySlot.UMG_InventorySlot_C.BndEvt__UMG_InventorySlot_UMG_STD_HotZone_K2Node_ComponentBoundEvent_2_OnSetUnselected__DelegateSignature
// (BlueprintEvent)

void UUMG_InventorySlot_C::BndEvt__UMG_InventorySlot_UMG_STD_HotZone_K2Node_ComponentBoundEvent_2_OnSetUnselected__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_InventorySlot_C", "BndEvt__UMG_InventorySlot_UMG_STD_HotZone_K2Node_ComponentBoundEvent_2_OnSetUnselected__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_InventorySlot.UMG_InventorySlot_C.BndEvt__UMG_InventorySlot_UMG_STD_HotZone_K2Node_ComponentBoundEvent_1_OnSetSelected__DelegateSignature
// (BlueprintEvent)

void UUMG_InventorySlot_C::BndEvt__UMG_InventorySlot_UMG_STD_HotZone_K2Node_ComponentBoundEvent_1_OnSetSelected__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_InventorySlot_C", "BndEvt__UMG_InventorySlot_UMG_STD_HotZone_K2Node_ComponentBoundEvent_1_OnSetSelected__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_InventorySlot.UMG_InventorySlot_C.K2_OnSelectCharacterSlot
// (Event, Protected, BlueprintEvent)

void UUMG_InventorySlot_C::K2_OnSelectCharacterSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_InventorySlot_C", "K2_OnSelectCharacterSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_InventorySlot.UMG_InventorySlot_C.BndEvt__UMG_InventorySlot_UMG_STD_HotZone_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature
// (BlueprintEvent)

void UUMG_InventorySlot_C::BndEvt__UMG_InventorySlot_UMG_STD_HotZone_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_InventorySlot_C", "BndEvt__UMG_InventorySlot_UMG_STD_HotZone_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UMG_InventorySlot.UMG_InventorySlot_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUMG_InventorySlot_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_InventorySlot_C", "OnFocusReceived");

	Params::UMG_InventorySlot_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

