#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_SettingMouseKeyboard

#include "Basic.hpp"


namespace SDK::Params
{

// Function UMG_SettingMouseKeyboard.UMG_SettingMouseKeyboard_C.ExecuteUbergraph_UMG_SettingMouseKeyboard
// 0x0088 (0x0088 - 0x0000)
struct UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_2;                // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_1;                // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index;                  // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	class UUMG_KeyBindingOptionItem_C*            K2Node_DynamicCast_AsUMG_Key_Binding_Option_Item;  // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue_1;             // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UPBOptions*                             CallFunc_GetEngineSubsystem_ReturnValue;           // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPBOptions*                             CallFunc_GetEngineSubsystem_ReturnValue_1;         // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0068(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0078(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard) == 0x000008, "Wrong alignment on UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard");
static_assert(sizeof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard) == 0x000088, "Wrong size on UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, EntryPoint) == 0x000000, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::EntryPoint' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, K2Node_ComponentBoundEvent_Index_2) == 0x000004, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::K2Node_ComponentBoundEvent_Index_2' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, K2Node_ComponentBoundEvent_Index_1) == 0x000008, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::K2Node_ComponentBoundEvent_Index_1' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, K2Node_ComponentBoundEvent_Index) == 0x00000C, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::K2Node_ComponentBoundEvent_Index' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, K2Node_DynamicCast_AsUMG_Key_Binding_Option_Item) == 0x000020, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::K2Node_DynamicCast_AsUMG_Key_Binding_Option_Item' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, CallFunc_GetDisplayName_ReturnValue) == 0x000030, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, CallFunc_GetActiveWidget_ReturnValue) == 0x000040, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, CallFunc_GetDisplayName_ReturnValue_1) == 0x000048, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::CallFunc_GetDisplayName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, CallFunc_GetEngineSubsystem_ReturnValue) == 0x000058, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::CallFunc_GetEngineSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, CallFunc_GetEngineSubsystem_ReturnValue_1) == 0x000060, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::CallFunc_GetEngineSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, K2Node_CreateDelegate_OutputDelegate_1) == 0x000068, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard, K2Node_CreateDelegate_OutputDelegate_2) == 0x000078, "Member 'UMG_SettingMouseKeyboard_C_ExecuteUbergraph_UMG_SettingMouseKeyboard::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");

// Function UMG_SettingMouseKeyboard.UMG_SettingMouseKeyboard_C.BndEvt__UMG_SettingMouseKeyboard_Card_Mouse_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Mouse_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Mouse_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature) == 0x000004, "Wrong alignment on UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Mouse_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature");
static_assert(sizeof(UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Mouse_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature) == 0x000004, "Wrong size on UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Mouse_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Mouse_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature, Index_0) == 0x000000, "Member 'UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Mouse_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature::Index_0' has a wrong offset!");

// Function UMG_SettingMouseKeyboard.UMG_SettingMouseKeyboard_C.BndEvt__UMG_SettingMouseKeyboard_Card_Keybinds_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Keybinds_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Keybinds_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature) == 0x000004, "Wrong alignment on UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Keybinds_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature");
static_assert(sizeof(UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Keybinds_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature) == 0x000004, "Wrong size on UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Keybinds_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Keybinds_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature, Index_0) == 0x000000, "Member 'UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Keybinds_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature::Index_0' has a wrong offset!");

// Function UMG_SettingMouseKeyboard.UMG_SettingMouseKeyboard_C.BndEvt__UMG_SettingMouseKeyboard_Card_Gameplay_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Gameplay_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Gameplay_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature) == 0x000004, "Wrong alignment on UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Gameplay_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature");
static_assert(sizeof(UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Gameplay_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature) == 0x000004, "Wrong size on UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Gameplay_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Gameplay_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature, Index_0) == 0x000000, "Member 'UMG_SettingMouseKeyboard_C_BndEvt__UMG_SettingMouseKeyboard_Card_Gameplay_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature::Index_0' has a wrong offset!");

// Function UMG_SettingMouseKeyboard.UMG_SettingMouseKeyboard_C.SwitchOptionList
// 0x0030 (0x0030 - 0x0000)
struct UMG_SettingMouseKeyboard_C_SwitchOptionList final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue_1;             // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_SettingMouseKeyboard_C_SwitchOptionList) == 0x000008, "Wrong alignment on UMG_SettingMouseKeyboard_C_SwitchOptionList");
static_assert(sizeof(UMG_SettingMouseKeyboard_C_SwitchOptionList) == 0x000030, "Wrong size on UMG_SettingMouseKeyboard_C_SwitchOptionList");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_SwitchOptionList, Index_0) == 0x000000, "Member 'UMG_SettingMouseKeyboard_C_SwitchOptionList::Index_0' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_SwitchOptionList, CallFunc_GetActiveWidget_ReturnValue) == 0x000008, "Member 'UMG_SettingMouseKeyboard_C_SwitchOptionList::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_SwitchOptionList, CallFunc_GetDisplayName_ReturnValue) == 0x000010, "Member 'UMG_SettingMouseKeyboard_C_SwitchOptionList::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_SwitchOptionList, CallFunc_GetDisplayName_ReturnValue_1) == 0x000020, "Member 'UMG_SettingMouseKeyboard_C_SwitchOptionList::CallFunc_GetDisplayName_ReturnValue_1' has a wrong offset!");

// Function UMG_SettingMouseKeyboard.UMG_SettingMouseKeyboard_C.On Use Option End Record
// 0x0040 (0x0040 - 0x0000)
struct UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record final
{
public:
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPBOptionBaseWidget*                    CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMG_Option_C*                          K2Node_DynamicCast_AsUMG_Option;                   // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMG_KeyBindingOptionItem_C*            K2Node_DynamicCast_AsUMG_Key_Binding_Option_Item;  // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record) == 0x000008, "Wrong alignment on UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record");
static_assert(sizeof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record) == 0x000040, "Wrong size on UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, Temp_int_Loop_Counter_Variable) == 0x000000, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, CallFunc_Add_IntInt_ReturnValue) == 0x000004, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, Temp_int_Array_Index_Variable) == 0x000008, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, CallFunc_Array_Get_Item) == 0x000010, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, CallFunc_IsValid_ReturnValue) == 0x00001C, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, CallFunc_Less_IntInt_ReturnValue) == 0x00001D, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, K2Node_DynamicCast_AsUMG_Option) == 0x000020, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::K2Node_DynamicCast_AsUMG_Option' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, K2Node_DynamicCast_AsUMG_Key_Binding_Option_Item) == 0x000030, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::K2Node_DynamicCast_AsUMG_Key_Binding_Option_Item' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record, CallFunc_IsValid_ReturnValue_1) == 0x000039, "Member 'UMG_SettingMouseKeyboard_C_On_Use_Option_End_Record::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

// Function UMG_SettingMouseKeyboard.UMG_SettingMouseKeyboard_C.RefreshAutoClimbExtraOption
// 0x0038 (0x0038 - 0x0000)
struct UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPBOptions*                             CallFunc_GetEngineSubsystem_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetEnumOption_ReturnValue;                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPBOptionBaseWidget*                    CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption) == 0x000008, "Wrong alignment on UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption");
static_assert(sizeof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption) == 0x000038, "Wrong size on UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption, Temp_int_Array_Index_Variable) == 0x000000, "Member 'UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption, CallFunc_GetEngineSubsystem_ReturnValue) == 0x000010, "Member 'UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption::CallFunc_GetEngineSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption, CallFunc_GetEnumOption_ReturnValue) == 0x000018, "Member 'UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption::CallFunc_GetEnumOption_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption, CallFunc_Array_Get_Item) == 0x000020, "Member 'UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000028, "Member 'UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption, CallFunc_Array_Length_ReturnValue) == 0x00002C, "Member 'UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption, CallFunc_Less_IntInt_ReturnValue) == 0x000030, "Member 'UMG_SettingMouseKeyboard_C_RefreshAutoClimbExtraOption::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function UMG_SettingMouseKeyboard.UMG_SettingMouseKeyboard_C.BP_GetDesiredFocusTarget
// 0x0050 (0x0050 - 0x0000)
struct UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0018(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMG_Option_C*                          K2Node_DynamicCast_AsUMG_Option;                   // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget) == 0x000050, "Wrong size on UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, Temp_int_Array_Index_Variable) == 0x000008, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, CallFunc_GetAllChildren_ReturnValue) == 0x000018, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, CallFunc_Array_Length_ReturnValue) == 0x000028, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, CallFunc_Array_Get_Item) == 0x000030, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, CallFunc_Less_IntInt_ReturnValue) == 0x000038, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, K2Node_DynamicCast_AsUMG_Option) == 0x000040, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::K2Node_DynamicCast_AsUMG_Option' has a wrong offset!");
static_assert(offsetof(UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'UMG_SettingMouseKeyboard_C_BP_GetDesiredFocusTarget::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

