#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_CharacterOption

#include "Basic.hpp"


namespace SDK::Params
{

// Function UMG_CharacterOption.UMG_CharacterOption_C.ExecuteUbergraph_UMG_CharacterOption
// 0x0004 (0x0004 - 0x0000)
struct UMG_CharacterOption_C_ExecuteUbergraph_UMG_CharacterOption final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UMG_CharacterOption_C_ExecuteUbergraph_UMG_CharacterOption) == 0x000004, "Wrong alignment on UMG_CharacterOption_C_ExecuteUbergraph_UMG_CharacterOption");
static_assert(sizeof(UMG_CharacterOption_C_ExecuteUbergraph_UMG_CharacterOption) == 0x000004, "Wrong size on UMG_CharacterOption_C_ExecuteUbergraph_UMG_CharacterOption");
static_assert(offsetof(UMG_CharacterOption_C_ExecuteUbergraph_UMG_CharacterOption, EntryPoint) == 0x000000, "Member 'UMG_CharacterOption_C_ExecuteUbergraph_UMG_CharacterOption::EntryPoint' has a wrong offset!");

}

