#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_OptionGroup

#include "Basic.hpp"

#include "UMG_OptionGroup_classes.hpp"
#include "UMG_OptionGroup_parameters.hpp"


namespace SDK
{

// Function UMG_OptionGroup.UMG_OptionGroup_C.ExecuteUbergraph_UMG_OptionGroup
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_OptionGroup_C::ExecuteUbergraph_UMG_OptionGroup(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_OptionGroup_C", "ExecuteUbergraph_UMG_OptionGroup");

	Params::UMG_OptionGroup_C_ExecuteUbergraph_UMG_OptionGroup Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_OptionGroup.UMG_OptionGroup_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_OptionGroup_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_OptionGroup_C", "PreConstruct");

	Params::UMG_OptionGroup_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

