#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeapomFireRocoil

#include "Basic.hpp"

#include "ProjectBoundary_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeapomFireRocoil.WeapomFireRocoil_C
// 0x0000 (0x01D0 - 0x01D0)
class UWeapomFireRocoil_C final : public UPBRecoilComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WeapomFireRocoil_C">();
	}
	static class UWeapomFireRocoil_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWeapomFireRocoil_C>();
	}
};
static_assert(alignof(UWeapomFireRocoil_C) == 0x000008, "Wrong alignment on UWeapomFireRocoil_C");
static_assert(sizeof(UWeapomFireRocoil_C) == 0x0001D0, "Wrong size on UWeapomFireRocoil_C");

}

