param([Parameter(Mandatory = $true)][string]$ReceiptPath)
Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
public static class StrictPackageWinTrust {
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] private struct WinTrustFileInfo { public uint cbStruct; public IntPtr pcwszFilePath; public IntPtr hFile; public IntPtr pgKnownSubject; }
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] private struct WinTrustData { public uint cbStruct; public IntPtr pPolicyCallbackData; public IntPtr pSIPClientData; public uint dwUIChoice; public uint fdwRevocationChecks; public uint dwUnionChoice; public IntPtr pFile; public uint dwStateAction; public IntPtr hWVTStateData; public IntPtr pwszURLReference; public uint dwProvFlags; public uint dwUIContext; }
    [DllImport("wintrust.dll", CharSet = CharSet.Unicode, SetLastError = true)] private static extern int WinVerifyTrust(IntPtr hwnd, ref Guid actionId, ref WinTrustData data);
    public static int Verify(string path) { IntPtr pathPtr=Marshal.StringToCoTaskMemUni(path); IntPtr filePtr=IntPtr.Zero; try { var file=new WinTrustFileInfo { cbStruct=(uint)Marshal.SizeOf<WinTrustFileInfo>(), pcwszFilePath=pathPtr }; filePtr=Marshal.AllocCoTaskMem(Marshal.SizeOf<WinTrustFileInfo>()); Marshal.StructureToPtr(file,filePtr,false); var data=new WinTrustData { cbStruct=(uint)Marshal.SizeOf<WinTrustData>(), dwUIChoice=2, dwUnionChoice=1, pFile=filePtr, dwStateAction=1 }; Guid action=new Guid("00AAC56B-CD44-11d0-8CC2-00C04FC295EE"); return WinVerifyTrust(IntPtr.Zero,ref action,ref data); } finally { if(filePtr!=IntPtr.Zero) Marshal.FreeCoTaskMem(filePtr); Marshal.FreeCoTaskMem(pathPtr); } }
}
"@
$ErrorActionPreference = 'Stop'; $CERT_E_UNTRUSTEDROOT = -2146762487; $EXPECTED_SIGNER_THUMBPRINT = 'B041917B2322ED509435B72356BA5AD9EA053378'
function Get-Sha256([string]$Path) { (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Fail([string]$Message) { throw "strict payload restore refused: $Message" }
function Assert-WinTrust([string]$Path, [string]$Label) { $h=[StrictPackageWinTrust]::Verify($Path); if ($h -ne 0 -and $h -ne $CERT_E_UNTRUSTEDROOT) { Fail "$Label WinVerifyTrust rejected with HRESULT $h" }; return $h }
function Assert-SignedArtifact([string]$Path, [string]$Label) { $signature=Get-AuthenticodeSignature -LiteralPath $Path; $thumbprint=if($signature.SignerCertificate){([string]$signature.SignerCertificate.Thumbprint).ToUpperInvariant()}else{''}; if($thumbprint -cne $EXPECTED_SIGNER_THUMBPRINT){Fail "$Label signer thumbprint is missing or unexpected"}; $h=Assert-WinTrust $Path $Label; return [ordered]@{hresult=$h;thumbprint=$thumbprint} }
function Assert-PackageManifest([string]$ManifestPath) {
    if (-not (Test-Path -LiteralPath $ManifestPath -PathType Leaf)) { Fail 'package-manifest.json is missing' }
    $package = Get-Content -LiteralPath $ManifestPath -Raw | ConvertFrom-Json
    if ([int]$package.schema_version -ne 1 -or [string]$package.purpose -cne 'hardware-test-only' -or [bool]$package.release_ready) { Fail 'package manifest is not a non-release hardware-test manifest' }
    $root = [IO.Path]::GetFullPath($PSScriptRoot).TrimEnd('\') + '\'; $entries = @($package.files)
    if ($entries.Count -eq 0) { Fail 'package manifest has no file entries' }
    foreach ($entry in $entries) {
        $relative = [string]$entry.path
        if ([string]::IsNullOrWhiteSpace($relative) -or $relative -match '(^[\\/]|^[A-Za-z]:|(^|[\\/])\.\.([\\/]|$))') { Fail "package manifest contains an unsafe path: $relative" }
        $full = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot $relative))
        if (-not $full.StartsWith($root, [StringComparison]::OrdinalIgnoreCase)) { Fail "package manifest path escapes package root: $relative" }
        if (-not (Test-Path -LiteralPath $full -PathType Leaf)) { Fail "package file is missing: $relative" }
        if ([long]$entry.bytes -ne (Get-Item -LiteralPath $full).Length -or [string]$entry.sha256 -cne (Get-Sha256 $full)) { Fail "package file bytes do not match manifest: $relative" }
    }
    foreach ($required in @('Payload.dll', 'rebound_toolbox_tauri.exe', 'Install-StrictPayload.ps1', 'Restore-StrictPayload.ps1', 'payload-manifest.json')) {
        if (-not @($entries | Where-Object { [string]$_.path -ceq $required }).Count) { Fail "package manifest omits required file: $required" }
    }
    return $package
}
$manifestPath=Join-Path $PSScriptRoot 'payload-manifest.json'; $toolboxPath=Join-Path $PSScriptRoot 'rebound_toolbox_tauri.exe'; $packagePayload=Join-Path $PSScriptRoot 'Payload.dll'
if (-not(Test-Path -LiteralPath $manifestPath -PathType Leaf) -or -not(Test-Path -LiteralPath $toolboxPath -PathType Leaf) -or -not(Test-Path -LiteralPath $packagePayload -PathType Leaf)) { Fail 'package manifest, Toolbox, or Payload.dll is missing' }
$packageManifest = Assert-PackageManifest (Join-Path $PSScriptRoot 'package-manifest.json')
$manifest=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json; if([string]$manifest.payload_filename -cne 'Payload.dll' -or [string]$manifest.toolbox_filename -cne 'rebound_toolbox_tauri.exe'){Fail 'manifest filenames are not the fixed package names'}; if([string]$manifest.signer_thumbprint -cne $EXPECTED_SIGNER_THUMBPRINT -or [string]$manifest.toolbox_signer_thumbprint -cne $EXPECTED_SIGNER_THUMBPRINT){Fail 'manifest signer thumbprint is not the pinned test signer'}; $expectedPayload=[string]$manifest.payload_sha256; $expectedGame=[string]$manifest.game_sha256; $expectedToolbox=[string]$manifest.toolbox_sha256; $expectedSteam=[string]$manifest.steam_api64_sha256
if($expectedPayload -notmatch '^[a-f0-9]{64}$' -or $expectedGame -notmatch '^[a-f0-9]{64}$' -or $expectedToolbox -notmatch '^[a-f0-9]{64}$' -or $expectedSteam -notmatch '^[a-f0-9]{64}$'){Fail 'package manifest hashes are incomplete'}; if((Get-Sha256 $packagePayload)-ne $expectedPayload -or (Get-Sha256 $toolboxPath)-ne $expectedToolbox){Fail 'package bytes do not match manifest'}
$payloadEntry=@($packageManifest.files|Where-Object{[string]$_.path -ceq 'Payload.dll'}); $toolboxEntry=@($packageManifest.files|Where-Object{[string]$_.path -ceq 'rebound_toolbox_tauri.exe'}); if($payloadEntry.Count -ne 1 -or [string]$payloadEntry[0].sha256 -cne $expectedPayload -or $toolboxEntry.Count -ne 1 -or [string]$toolboxEntry[0].sha256 -cne $expectedToolbox){Fail 'package-manifest and payload-manifest disagree about signed artifact bytes'}; if([string]$packageManifest.pinned_game.sha256 -cne $expectedGame){Fail 'package-manifest and payload-manifest disagree about game pin'}
$toolboxSignature=Assert-SignedArtifact $toolboxPath 'Toolbox'; $payloadSignature=Assert-SignedArtifact $packagePayload 'Payload'; $name=[IO.Path]::GetFileNameWithoutExtension($toolboxPath); if(Get-Process -Name $name -ErrorAction SilentlyContinue){Fail 'Toolbox process is running; close it and retry'}; if(Get-Process -Name 'ProjectBoundarySteam-Win64-Shipping' -ErrorAction SilentlyContinue){Fail 'game process is running; close it and retry'}
$receipt=Get-Content -LiteralPath (Resolve-Path -LiteralPath $ReceiptPath -ErrorAction Stop) -Raw|ConvertFrom-Json; if([string]$receipt.operation -ne 'install'){Fail 'receipt is not an install receipt'}; $gameRoot=(Resolve-Path -LiteralPath ([string]$receipt.game_win64) -ErrorAction Stop).Path; if((Split-Path -Leaf $gameRoot)-cne 'Win64'){Fail 'receipt target is not a Win64 directory'}
$gameExe=Join-Path $gameRoot 'ProjectBoundarySteam-Win64-Shipping.exe'; if(-not(Test-Path -LiteralPath $gameExe -PathType Leaf)){Fail 'receipt target game executable is missing'}; if((Get-Sha256 $gameExe)-ne ([string]$receipt.game_executable_sha256).ToLowerInvariant() -or (Get-Sha256 $gameExe)-ne $expectedGame){Fail 'target game executable changed or has the wrong strict hash'}
$steamDll=Join-Path $gameRoot '..\..\..\Engine\Binaries\ThirdParty\Steamworks\Steamv157\Win64\steam_api64.dll'; if(-not(Test-Path -LiteralPath $steamDll -PathType Leaf)){Fail 'Steam runtime is missing'}; if((Get-Sha256 $steamDll)-cne $expectedSteam){Fail 'Steam runtime hash does not match the package path pin'}; $destination=Join-Path $gameRoot 'Payload.dll'; $backupPath=[string]$receipt.backup_path; if(-not(Test-Path -LiteralPath $backupPath -PathType Leaf)){Fail 'receipt backup is missing'}; if((Get-Sha256 $backupPath)-ne ([string]$receipt.backup_sha256).ToLowerInvariant()){Fail 'backup bytes no longer match receipt'}; if(-not(Test-Path -LiteralPath $destination -PathType Leaf)){Fail 'installed Payload.dll is missing'}; if((Get-Sha256 $destination)-ne ([string]$receipt.installed_payload_sha256).ToLowerInvariant()){Fail 'current Payload.dll changed after install; refusing to overwrite it'}
$tempPath=Join-Path $gameRoot ('.Payload.dll.strict-restore-'+[Guid]::NewGuid().ToString('N')+'.tmp'); try { Copy-Item -LiteralPath $backupPath -Destination $tempPath -ErrorAction Stop; if((Get-Sha256 $tempPath)-ne ([string]$receipt.backup_sha256).ToLowerInvariant()){Fail 'temporary restore copy failed hash verification'}; Move-Item -LiteralPath $tempPath -Destination $destination -Force -ErrorAction Stop; if((Get-Sha256 $destination)-ne ([string]$receipt.backup_sha256).ToLowerInvariant()){Fail 'restored Payload.dll failed final hash verification'}; [ordered]@{schema_version=1;operation='restore';status='completed';game_win64=$gameRoot;restored_payload_sha256=Get-Sha256 $destination;source_backup=$backupPath;toolbox_winverifytrust_hresult=$toolboxSignature.hresult;toolbox_signer_thumbprint=$toolboxSignature.thumbprint;payload_winverifytrust_hresult=$payloadSignature.hresult;payload_signer_thumbprint=$payloadSignature.thumbprint;steam_api64_sha256=$expectedSteam;completed_at=[DateTime]::UtcNow.ToString('o')}|ConvertTo-Json -Depth 5 } catch { if(Test-Path -LiteralPath $tempPath){Remove-Item -LiteralPath $tempPath -Force -ErrorAction SilentlyContinue}; throw }
